services:
  discv:
    image: "janus"
    # You can build remotely the docker image by uncommenting this line and commenting the other `build`
    # build: https://github.com/cyber-coop/eth-node-finder.git
    build: .
    container_name: discv
    pull_policy: never
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config.toml:/config.toml
    command: discv
    ports:
      - "0.0.0.0:30303:30303/udp"

  ping:
    image: "janus"
    # build: https://github.com/cyber-coop/eth-node-finder.git
    build: .
    container_name: ping
    pull_policy: never
    depends_on:
      postgres:
        condition: service_healthy
      discv:
        condition: service_started
    volumes:
      - ./config.toml:/config.toml
    command: ping

  server:
    image: "janus"
    # build: https://github.com/cyber-coop/eth-node-finder.git
    build: .
    container_name: server
    pull_policy: never
    depends_on:
      postgres:
        condition: service_healthy
      discv:
        condition: service_started
    volumes:
      - ./config.toml:/config.toml
    command: server
    ports:
      - "0.0.0.0:50505:50505/tcp"
      - "0.0.0.0:50505:50505/udp"

  status:
    image: "janus"
    build: https://github.com/cyber-coop/eth-node-finder.git
    container_name: status
    pull_policy: never
    depends_on:
      postgres:
        condition: service_healthy
      discv:
        condition: service_started
    volumes:
      - ./config.toml:/config.toml
    command: status

  postgres:
    image: "postgres:18"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blockchains
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # This has been changed in postgres 18
      - ./data/:/var/lib/postgresql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
